<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class FoodTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    /**
     * @test
     */
    public function it_creates_food_successfully(){

        $params = [
            'name' => 'Chicken and Rice',
            'price' => 3.99,
        ];

        $response = $this->post('/food', $params);

        $response->assertCreated();
    }

    

}
